apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: miniws
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: trand-ws
        image: trand/miniws
        imagePullPolicy: Never